export const teamData = [
  {
    ImgUrl: "team.png",
    Name: "Name1",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
 
  {
    ImgUrl: "team.png",
    Name: "Name1",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name1",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name1",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name1",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
];

export const CPData = [
  {
    ImgUrl: "team.png",
    Name: "Name2",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name2",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name2",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name2",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name2",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
];

export const WebDevData = [
  {
    ImgUrl: "team.png",
    Name: "Name3",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name3",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name3",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name3",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
  {
    ImgUrl: "team.png",
    Name: "Name3",
    Linkedin: "https://reactjs.org/",
    Github: "https://reactjs.org/",
    Twitter: "https://reactjs.org/",
    Instagram: "https://reactjs.org/",
  },
];
