export const teamData = [
  {
    ImgUrl: "team.png",
    Name: "Shubhankar Sharma",
    Linkedin: "https://www.linkedin.com/in/shubhankar-sharma/",
    Github: "https://github.com/Silver-Whiskey",
    Twitter: "https://twitter.com/Shubhan65135975",
    Instagram: "https://www.instagram.com/vashishthshubhankar99/",
  },
];

export const CPData = [
  {
    ImgUrl: "team.png",
    Name: "Sahil soni",
    Linkedin: "https://www.linkedin.com/in/sahil-soni-1a90591b7/",
    Github: "https://github.com/sahil801",
    Twitter: "",
    Instagram: "https://www.instagram.com/sahilsoni_88/",
  },
  {
    ImgUrl: "team.png",
    Name: "Asmit Pandey ",
    Linkedin: "https://www.linkedin.com/in/asmit-pandey-170764207",
    Github: "",
    Twitter: "",
    Instagram: "https://www.instagram.com/asmit0701/",
  },
  {
    ImgUrl: "team.png",
    Name: "Parth Chandan",
    Linkedin: "https://www.linkedin.com/in/parth-chandan-pc283",
    Github: "",
    Twitter: "",
    Instagram: "",
  },
  {
    ImgUrl: "team.png",
    Name: "Nakshatra",
    Linkedin: "https://www.linkedin.com/in/nakshatra-138b28214",
    Github: "https://github.com/Nakxtra",
    Twitter: "https://reactjs.org/",
    Instagram: "http://instagram.com/basically_nakshatra?utm_source=qr",
  },
  {
    ImgUrl: "team.png",
    Name: "Saurabh Anand",
    Linkedin: "https://www.linkedin.com/in/saurabh-singh-12a047203",
    Github: "",
    Twitter: "",
    Instagram: "",
  },
  {
    ImgUrl: "team.png",
    Name: "Sanskar Asati ",
    Linkedin: "https://www.linkedin.com/in/sanskar-asati-184290202",
    Github: "",
    Twitter: "",
    Instagram: "https://www.instagram.com/invites/contact/?i=h6fjdbrkb9bt&utm_content=1xcjbwy",
  },
  {
    ImgUrl: "team.png",
    Name: "Shivansh Gupta",
    Linkedin: "https://www.linkedin.com/in/shivansh-gupta-b08561201/",
    Github: "https://github.com/shivanshguptasg49",
    Twitter: "",
    Instagram: "",
  },
  {
    ImgUrl: "team.png",
    Name: "Harshit Chaudhary",
    Linkedin: "https://www.linkedin.com/in/harshit-chaudhary-8b0783206",
    Github: "https://github.com/dnharshit",
    Twitter: "https://twitter.com/dnharshit",
    Instagram: "https://www.instagram.com/dnharshit/",
  },
  {
    ImgUrl: "team.png",
    Name: "Gaurav Kumar",
    Linkedin: "https://www.linkedin.com/in/devil-x/",
    Github: "https://github.com/The-Gaurav-Kumar",
    Twitter: "",
    Instagram: "https://www.instagram.com/iegaurav/",
  },
  {
    ImgUrl: "team.png",
    Name: "Ansh Varshney",
    Linkedin: "https://www.linkedin.com/in/ansh-varshney-55060921a",
    Github: "",
    Twitter: "",
    Instagram: "",
  },
  {
    ImgUrl: "team.png",
    Name: "Pratyaksh Gupta",
    Linkedin: "https://www.linkedin.com/in/gupta-pratyaksh/",
    Github: "",
    Twitter: "",
    Instagram: "https://www.instagram.com/_pratyaksh_gupta/",
  },
  {
    ImgUrl: "team.png",
    Name: "Pradeep Kumar Sahu",
    Linkedin: "https://www.linkedin.com/in/pradeep-k-sahu/",
    Github: "https://github.com/pradeep891",
    Twitter: "",
    Instagram: "https://www.instagram.com/pradeep.k_s/",
  },
  {
    ImgUrl: "team.png",
    Name: "Aman Gupta",
    Linkedin: "https://www.linkedin.com/in/aman-gupta-43b5111b8/",
    Github: "",
    Twitter: "",
    Instagram: "",
  },
];

export const WebDevData = [
  {
    ImgUrl: "team.png",
    Name: "Mohit Khairnar",
    Linkedin: "https://www.linkedin.com/in/mohit-khairnar/",
    Github: "https://github.com/mohittk",
    Twitter: "https://twitter.com/MohitKhairnar12",
    Instagram: "https://www.instagram.com/mohitt_khairnar/",
  },
  {
    ImgUrl: "team.png",
    Name: "Nitin Gupta",
    Linkedin: "https://www.linkedin.com/in/nitin-gupta-b915a81ba/",
    Github: "https://github.com/nitingupta-max",
    Twitter: "https://twitter.com/NitinGu13499448",
    Instagram: "https://www.instagram.com/nitin_gupta_i20i/",
  },
  {
    ImgUrl: "team.png",
    Name: "Badri Vishal Singhal",
    Linkedin: "https://in.linkedin.com/in/badri-vishal-singhal",
    Github: "https://github.com/vishal8803",
    Twitter: "",
    Instagram: "",
  },
  {
    ImgUrl: "team.png",
    Name: "Ujjwal Gupta",
    Linkedin: "https://www.linkedin.com/in/ujjwal-gupta-65966a1b2",
    Github: "https://github.com/Ujjwal-Gupta-web",
    Twitter: "",
    Instagram: "https://www.instagram.com/ujjwal.gupta9/",
  },
  {
    ImgUrl: "team.png",
    Name: "Rishabh Agnihotri",
    Linkedin: "https://www.linkedin.com/in/rishabh-agnihotri-07b9a2200/",
    Github: "https://github.com/agnihotri099",
    Twitter: "https://twitter.com/rishabh_agni5",
    Instagram: "https://www.instagram.com/rishabh_agni/",
  },
  {
    ImgUrl: "team.png",
    Name: "Mitushi Agrawal",
    Linkedin: "https://www.linkedin.com/in/mitushi-agrawal-bb75b0210/",
    Github: "https://github.com/Mitushi-23",
    Twitter: "https://mobile.twitter.com/mitushi_agrawal",
    Instagram: "https://www.instagram.com/mitushi_agrawal_/",
  },
];
